# Generated by Django 5.1.3 on 2025-03-19 20:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="",  # Não execute nada, pois a tabela já existe
            reverse_sql="",  # Não execute nada ao reverter
            state_operations=[
                migrations.CreateModel(
                    name='MensagemAosNoivos',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('texto_mensagem', models.TextField()),
                        ('data_envio', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_aos_noivos', to='auth.User')),
                        ('escrita_por', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='noivos.Convidados')),
                    ],
                ),
            ],
        ),
    ]
