# Generated by Django 5.1.3 on 2025-03-26 00:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0002_auto_20250319_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemaosnoivos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagemaosnoivos',
            name='texto_mensagem',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
