# Generated by Django 5.1.3 on 2025-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_alter_mensagemaosnoivos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='mensagem_noivos',
            field=models.TextField(blank=True, default='O grande dia está chegando e estamos cheios de alegria por poder compartilhar com nossa família e amigos um dos momentos mais especiais de nossas vidas! Será um dia repleto de amor, diversão e muita emoção, e queremos muito contar com sua presença para tornar essa celebração ainda mais inesquecível. Vamos comemorar juntos e criar memórias que ficarão para sempre em nossos corações!', null=True),
        ),
    ]
