# Generated by Django 5.1.3 on 2025-04-02 23:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0004_alter_perfil_mensagem_noivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemaosnoivos',
            name='texto_mensagem',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
