# Generated by Django 5.1.2 on 2024-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0004_acompanhante'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentes',
            name='link_sugestao_compra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentes',
            name='foto',
            field=models.ImageField(upload_to='presentes/'),
        ),
        migrations.AlterField(
            model_name='presentes',
            name='importancia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presentes',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentes',
            name='reservado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
