# Generated by Django 5.1.3 on 2025-04-02 23:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0005_alter_mensagemaosnoivos_texto_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemaosnoivos',
            name='texto_mensagem',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
