# Generated by Django 5.1.3 on 2025-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0006_alter_mensagemaosnoivos_texto_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsobrenoivonoiva',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
    ]
