# Generated by Django 5.1.2 on 2024-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0006_alter_presentes_reservado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='link_sugestao_compra',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
