# Generated by Django 5.2 on 2025-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0007_alter_mensagemsobrenoivonoiva_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='link_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
