# Generated by Django 5.1.3 on 2024-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0007_alter_presentes_link_sugestao_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidados',
            name='nome_convidado',
            field=models.CharField(max_length=255),
        ),
    ]
