# Generated by Django 5.2 on 2025-04-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0008_convidados_link_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidados',
            name='link_whatsapp',
        ),
    ]
