# Generated by Django 5.1.3 on 2024-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0008_alter_convidados_nome_convidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentes',
            name='link_cobranca',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='maximo_acompanhantes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='nome_convidado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
