# Generated by Django 5.1.3 on 2024-11-28 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0009_presentes_link_cobranca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentes',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='presentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
