# Generated by Django 5.2 on 2025-05-17 19:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0009_remove_convidados_link_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos_base/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link_sugestao_compra', models.URLField(blank=True, max_length=1000, null=True)),
                ('link_cobranca', models.URLField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('importancia', models.IntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='presentes',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 17, 16, 15, 18, 940624)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentes',
            name='produto_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noivos.produtobase'),
        ),
    ]
