# Generated by Django 5.2 on 2025-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0010_produtobase_presentes_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='presentes/'),
        ),
    ]
