# Generated by Django 5.1.3 on 2024-12-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0012_alter_convidados_user_alter_presentes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noivos.convidados'),
        ),
    ]
