# Generated by Django 5.1.3 on 2024-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0013_alter_presentes_reservado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='mensagem_personalizada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
