# Generated by Django 5.1.3 on 2024-12-04 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0014_convidados_mensagem_personalizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidados',
            name='mensagem_personalizada',
        ),
        migrations.CreateModel(
            name='MensagemPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
