# Generated by Django 5.1.3 on 2024-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0016_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome_companheiro',
            new_name='nome_primeiro_conjuge',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_segundo_conjuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
