# Generated by Django 5.1.3 on 2024-12-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0017_rename_nome_companheiro_perfil_nome_primeiro_conjuge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='presentes/'),
        ),
    ]
