# Generated by Django 5.1.3 on 2024-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0018_alter_presentes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='endereco_festa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_perfil/'),
        ),
    ]
