# Generated by Django 5.1.3 on 2024-12-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0019_perfil_endereco_festa_perfil_imagem_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='imagem_perfil',
            new_name='imagem',
        ),
    ]
