# Generated by Django 5.1.3 on 2024-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0022_remove_perfil_endereco_festa_perfil_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
