# Generated by Django 5.1.3 on 2024-12-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0023_perfil_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='mensagem',
            new_name='mensagem_noivos',
        ),
    ]
