# Generated by Django 5.1.3 on 2024-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0024_rename_mensagem_perfil_mensagem_noivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/'),
        ),
    ]
