# Generated by Django 5.1.3 on 2024-12-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0025_mensagempersonalizada_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagempersonalizada',
            name='arquivo',
        ),
    ]
