# Generated by Django 5.1.3 on 2024-12-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0026_remove_mensagempersonalizada_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/'),
        ),
    ]
