# Generated by Django 5.1.3 on 2024-12-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0028_remove_mensagempersonalizada_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagempersonalizada',
            name='arquivo_base64',
        ),
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
