# Generated by Django 5.1.3 on 2024-12-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0029_remove_mensagempersonalizada_arquivo_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='arquivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
