# Generated by Django 5.1.3 on 2024-12-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0030_alter_mensagempersonalizada_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagempersonalizada',
            old_name='arquivo',
            new_name='arquivo_base64',
        ),
    ]
