# Generated by Django 5.1.3 on 2024-12-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0031_rename_arquivo_mensagempersonalizada_arquivo_base64'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagempersonalizada',
            name='arquivo_base64',
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_personalizada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArquivoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/mensagens/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_mensagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
