# Generated by Django 5.1.3 on 2024-12-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0032_remove_mensagempersonalizada_arquivo_base64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='arquivo_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_personalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ArquivoMensagem',
        ),
    ]
