# Generated by Django 5.1.3 on 2024-12-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0033_mensagempersonalizada_arquivo_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagempersonalizada',
            name='arquivo_base64',
        ),
    ]
