# Generated by Django 5.1.3 on 2024-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0034_remove_mensagempersonalizada_arquivo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mensagens_imagens/'),
        ),
    ]
