# Generated by Django 5.1.3 on 2025-03-11 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0037_imagemgaleria_imagemnoivos_mensagemsobrenoivonoiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='link_sugestao_compra',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagems_galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='noivos.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemSobreNoivoNoiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noiva', 'Noiva'), ('noivo', 'Noivo')], max_length=10)),
                ('mensagem', models.TextField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='noivos.perfil')),
            ],
        ),
    ]
