# Generated by Django 5.1.3 on 2025-02-18 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0037_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagems_galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='noivos.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
