# Generated by Django 5.1.3 on 2025-03-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0038_alter_presentes_link_sugestao_compra_imagemgaleria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='nome_presente',
            field=models.CharField(max_length=500),
        ),
    ]
