# Generated by Django 5.1.3 on 2025-02-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0038_imagemgaleria_delete_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSobreNoivoNoiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noiva', 'Noiva'), ('noivo', 'Noivo')], max_length=10)),
                ('mensagem', models.TextField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='noivos.perfil')),
            ],
        ),
    ]
