# Generated by Django 5.1.3 on 2025-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0039_alter_presentes_nome_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentes',
            name='nome_presente',
            field=models.CharField(max_length=1000),
        ),
    ]
