# Generated by Django 5.1.3 on 2025-02-22 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0039_mensagemsobrenoivonoiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemNoivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagems_noivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('tipo', models.CharField(choices=[('noiva', 'Noiva'), ('noivo', 'Noivo')], max_length=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosnoivos', to='noivos.perfil')),
            ],
        ),
    ]
