# Generated by Django 5.1.3 on 2025-03-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0040_alter_presentes_nome_presente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=1000)),
                ('link_sugestao_compra', models.URLField(blank=True, null=True)),
                ('link_cobranca', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importancia', models.IntegerField(choices=[(1, 'Pouco Importante'), (2, 'Pouco Importante'), (3, 'Importante'), (4, 'Muito Importante'), (5, 'Muito Importante')], default=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
