# Generated by Django 5.1.3 on 2025-03-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0041_produtolista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtolista',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produtolista',
            name='link_cobranca',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produtolista',
            name='link_sugestao_compra',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
