# Generated by Django 5.1.3 on 2025-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0042_alter_produtolista_imagem_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoLista',
        ),
        migrations.AddField(
            model_name='perfil',
            name='horario_casamento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
